[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "P68688"
path = "src/bin/first-programs/P68688/main.rs"

[[bin]]
name ="P41221"
path = "src/bin/first-programs/P41221/main.rs"

[[bin]]
name = "P48107"
path = "src/bin/first-programs/P48107/main.rs"

[[bin]]
name = "P57548"
path = "src/bin/first-programs/P57548/main.rs"

[[bin]]
name = "P58294"
path = "src/bin/first-programs/P58294/main.rs"

[[bin]]
name = "P70955"
path = "src/bin/first-programs/P70955/main.rs"

[[bin]]
name = "P92351"
path = "src/bin/first-programs/P92351/main.rs"

[[bin]]
name = "P15613"
path = "src/bin/alternatives/P15613/main.rs"

[[bin]]
name = "P34279"
path = "src/bin/alternatives/P34279/main.rs"

[[bin]]
name = "P37469"
path = "src/bin/alternatives/P37469/main.rs"

[[bin]]
name = "P42042"
path = "src/bin/alternatives/P42042/main.rs"

[[bin]]
name = "P52847"
path = "src/bin/alternatives/P52847/main.rs"

[[bin]]
name = "P56118"
path = "src/bin/alternatives/P56118/main.rs"

[[bin]]
name = "P59539"
path = "src/bin/alternatives/P59539/main.rs"

[[bin]]
name = "P90615"
path = "src/bin/alternatives/P90615/main.rs"

[[bin]]
name = "P97156"
path = "src/bin/alternatives/P97156/main.rs"

[[bin]]
name = "P98960"
path = "src/bin/alternatives/P98960/main.rs"

[[bin]]
name = "P28754"
path = "src/bin/alternatives_and_iterations/P28754/main.rs"

[[bin]]
name = "P29448"
path = "src/bin/alternatives_and_iterations/P29448/main.rs"

[[bin]]
name = "P31170"
path = "src/bin/alternatives_and_iterations/P31170/main.rs"

[[bin]]
name = "P35547"
path = "src/bin/alternatives_and_iterations/P35547/main.rs"

[[bin]]
name = "P36668"
path = "src/bin/alternatives_and_iterations/P36668/main.rs"

[[bin]]
name = "P37500"
path = "src/bin/alternatives_and_iterations/P37500/main.rs"

[[bin]]
name = "P39057"
path = "src/bin/alternatives_and_iterations/P39057/main.rs"

[[bin]]
name = "P43850"
path = "src/bin/alternatives_and_iterations/P43850/main.rs"

[[bin]]
name = "P50327"
path = "src/bin/alternatives_and_iterations/P50327/main.rs"

[[bin]]
name = "P51126"
path = "src/bin/alternatives_and_iterations/P51126/main.rs"

[[bin]]
name = "P55622"
path = "src/bin/alternatives_and_iterations/P55622/main.rs"

[[bin]]
name = "P56559"
path = "src/bin/alternatives_and_iterations/P56559/main.rs"

[[bin]]
name = "P59875"
path = "src/bin/alternatives_and_iterations/P59875/main.rs"

[[bin]]
name = "P60816"
path = "src/bin/alternatives_and_iterations/P60816/main.rs"